import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, FileSignature, Building2, Calendar, CheckCircle, Loader } from 'lucide-react';
import { collection, getDocs, orderBy, query } from 'firebase/firestore';
import { db } from '../firebase';

export default function ReportsTab() {
  const [downloaded, setDownloaded] = useState<string | null>(null);
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchReports = async () => {
      try {
        const eventsRef = collection(db, 'events');
        // No orderBy just in case index is missing, simple getDocs
        const snapshot = await getDocs(eventsRef);
        const fetchedReports = snapshot.docs.map(doc => {
          const data = doc.data();
          return {
            id: doc.id,
            facility: data.kitchen_id || 'Unknown Facility',
            date: new Date().toLocaleDateString(), // No timestamp in backend data, fallback to today
            type: data.status === 'ambiguous' ? 'Agent Debate Event' : 'Vision Inference Event',
            status: 'Generated',
            summary: `Risk Score: ${data.risk_score}. Justification: ${data.justification}`,
            transcript: data.transcript,
            risk_score: data.risk_score
          };
        });
        setReports(fetchedReports);
      } catch (err) {
        console.error('Error fetching reports from Firestore:', err);
      } finally {
        setLoading(false);
      }
    };
    fetchReports();
  }, []);

  const handleDownload = (report) => {
    setDownloaded(report.id);
    
    let content = `AAHAAR-AUDIT OFFICIAL REGULATORY DOSSIER\n`;
    content += `=========================================\n`;
    content += `Facility: ${report.facility}\n`;
    content += `Date: ${report.date}\n`;
    content += `Event Type: ${report.type}\n`;
    content += `Risk Score: ${report.risk_score}\n\n`;
    content += `SUMMARY:\n${report.summary}\n\n`;
    
    if (report.transcript && report.transcript.length > 0) {
      content += `AGENT DEBATE TRANSCRIPT:\n`;
      content += `------------------------\n`;
      report.transcript.forEach((msg) => {
        content += `[${msg.role.toUpperCase()}]\n${msg.content}\n\n`;
      });
    }
    
    content += `=========================================\n`;
    content += `Auto-Generated by Aahaar-Audit Report Agent`;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Audit_Report_${report.facility.replace(/\s+/g, '_')}_${report.id.substring(0,6)}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-5xl mx-auto h-full flex flex-col gap-6">
      <div className="flex justify-between items-center mb-2">
        <h2 className="text-xl font-bold text-emerald-950">Regulatory Report Agent</h2>
        <span className="text-sm font-mono text-emerald-600">Auto-Generated Dossiers</span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {loading ? (
          <div className="flex items-center justify-center p-8 w-full col-span-2 text-emerald-600">
            <Loader className="w-8 h-8 animate-spin" />
            <span className="ml-3 font-mono">Fetching reports from Firestore...</span>
          </div>
        ) : reports.length === 0 ? (
          <div className="flex items-center justify-center p-8 w-full col-span-2 text-emerald-600 font-mono">
            No reports found in the database.
          </div>
        ) : (
          reports.map((report, i) => (
            <motion.div
              key={report.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="glass-panel p-6 flex flex-col justify-between"
          >
            <div>
              <div className="flex justify-between items-start mb-4">
                <div className="bg-white p-3 rounded-lg border border-emerald-200">
                  <FileSignature className="w-6 h-6 text-emerald-600" />
                </div>
                <span className={`text-xs px-2 py-1 rounded-full border font-medium ${
                  report.status === 'Generated' ? 'bg-brand-green/20 text-brand-green border-brand-green/30' : 'bg-amber-500/20 text-amber-400 border-amber-500/30'
                }`}>
                  {report.status}
                </span>
              </div>
              
              <h3 className="text-lg font-bold text-emerald-950 mb-2">{report.facility}</h3>
              
              <div className="flex gap-4 text-xs text-emerald-600 mb-4 font-mono">
                <span className="flex items-center gap-1"><Calendar className="w-3 h-3" /> {report.date}</span>
                <span className="flex items-center gap-1"><FileText className="w-3 h-3" /> {report.type}</span>
              </div>

              <div className="bg-emerald-50/80 p-3 rounded border border-emerald-200 mb-6">
                <p className="text-sm text-emerald-800 italic text-justify leading-relaxed">
                  "{report.summary}"
                </p>
                <p className="text-xs text-emerald-500 mt-2 flex justify-end">— Auto-generated by Report Agent</p>
              </div>
            </div>

            <button 
              onClick={() => handleDownload(report)}
              disabled={report.status !== 'Generated'}
              className={`w-full py-3 rounded flex items-center justify-center gap-2 font-bold text-sm transition-all ${
                downloaded === report.id 
                  ? 'bg-brand-green/20 text-brand-green border border-brand-green/50 cursor-default'
                  : report.status !== 'Generated'
                    ? 'bg-white text-emerald-500 cursor-not-allowed border border-emerald-200'
                    : 'bg-emerald-100 hover:bg-navy-600 text-emerald-900 border border-emerald-200'
              }`}
            >
              {downloaded === report.id ? (
                <><CheckCircle className="w-4 h-4" /> Downloaded successfully!</>
              ) : (
                <><Download className="w-4 h-4" /> Download Official Dossier</>
              )}
            </button>
          </motion.div>
        )))}
      </div>
    </div>
  );
}
