import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, FileSignature, Building2, Calendar, CheckCircle } from 'lucide-react';

export default function ReportsTab() {
  const [downloaded, setDownloaded] = useState<string | null>(null);

  const reports = [
    { id: 'rep-1', facility: 'Dadar Dark Store #58', date: 'Oct 12, 2023', type: 'Routine Audit + AI Flag', status: 'Generated', summary: 'Facility flagged for severe hygiene violations (gloves not used). Multiple compliance failures noted in storage temperature logs.' },
    { id: 'rep-2', facility: 'Bandra Central Kitchen', date: 'Oct 10, 2023', type: 'Supplier Traceability', status: 'Generated', summary: 'Traceability audit completed successfully. Supplier records match physical inventory for 98% of monitored high-risk items.' },
    { id: 'rep-3', facility: 'Nashik Fresh Bites', date: 'Oct 09, 2023', type: 'Complaint Investigation', status: 'Pending Review', summary: 'Investigation initiated based on 4 clustered public health complaints. Temperature violation evidence gathered from IoT sensors.' },
    { id: 'rep-4', facility: 'Pune Express Foods', date: 'Sep 25, 2023', type: 'Routine Audit', status: 'Generated', summary: 'General compliance maintained. Minor recommendations for better segregation of raw and cooked items provided.' },
  ];

  return (
    <div className="max-w-5xl mx-auto h-full flex flex-col gap-6">
      <div className="flex justify-between items-center mb-2">
        <h2 className="text-xl font-bold text-emerald-950">Regulatory Report Agent</h2>
        <span className="text-sm font-mono text-emerald-600">Auto-Generated Dossiers</span>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {reports.map((report, i) => (
          <motion.div
            key={report.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="glass-panel p-6 flex flex-col justify-between"
          >
            <div>
              <div className="flex justify-between items-start mb-4">
                <div className="bg-white p-3 rounded-lg border border-emerald-200">
                  <FileSignature className="w-6 h-6 text-emerald-600" />
                </div>
                <span className={`text-xs px-2 py-1 rounded-full border font-medium ${
                  report.status === 'Generated' ? 'bg-brand-green/20 text-brand-green border-brand-green/30' : 'bg-amber-500/20 text-amber-400 border-amber-500/30'
                }`}>
                  {report.status}
                </span>
              </div>
              
              <h3 className="text-lg font-bold text-emerald-950 mb-2">{report.facility}</h3>
              
              <div className="flex gap-4 text-xs text-emerald-600 mb-4 font-mono">
                <span className="flex items-center gap-1"><Calendar className="w-3 h-3" /> {report.date}</span>
                <span className="flex items-center gap-1"><FileText className="w-3 h-3" /> {report.type}</span>
              </div>

              <div className="bg-emerald-50/80 p-3 rounded border border-emerald-200 mb-6">
                <p className="text-sm text-emerald-800 italic text-justify leading-relaxed">
                  "{report.summary}"
                </p>
                <p className="text-xs text-emerald-500 mt-2 flex justify-end">— Auto-generated by Report Agent</p>
              </div>
            </div>

            <button 
              onClick={() => setDownloaded(report.id)}
              disabled={report.status !== 'Generated'}
              className={`w-full py-3 rounded flex items-center justify-center gap-2 font-bold text-sm transition-all ${
                downloaded === report.id 
                  ? 'bg-brand-green/20 text-brand-green border border-brand-green/50 cursor-default'
                  : report.status !== 'Generated'
                    ? 'bg-white text-emerald-500 cursor-not-allowed border border-emerald-200'
                    : 'bg-emerald-100 hover:bg-navy-600 text-emerald-900 border border-emerald-200'
              }`}
            >
              {downloaded === report.id ? (
                <><CheckCircle className="w-4 h-4" /> Downloaded</>
              ) : (
                <><Download className="w-4 h-4" /> Download Official PDF</>
              )}
            </button>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
